### Register User
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "user6",
    "email": "user6@example.com",
    "password": "password123"
}

### Login User
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "user1@example.com",
    "password": "password123"
}

### Get All Users
GET http://localhost:3000/users
Content-Type: application/json

### Get All Users and count
GET http://localhost:3000/users/count
Content-Type: application/json
### Get User By Id
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGV4YW1wbGUuY29tIiwiaWF0IjoxNzM3NTU0NTY4LCJleHAiOjE3Mzc1NTgxNjh9.PpxXtzMWMtTuC5FMLNCvCGl4QYqYj7kjpXabhjgGB-Y
GET http://localhost:3000/users/678e4ada90f3aec4253bf6e7
Content-Type: application/json
Authorization: {{token}}

### Update User
PUT http://localhost:3000/users/678e4ada90f3aec4253bf6e7
Content-Type: application/json

{
    "name": "user1_up",
    "email": "user1@example.com"
}

### Delete User
DELETE http://localhost:3000/users/678e4ab190f3aec4253bf6e4
Content-Type: application/json
